[[redirects]] # cuando hacemos click en ver todos los articulos, ir al index del Blog
  from = '/blogs' 
  to = 'http://15.222.45.215/'
  status = 200
  force = true

[[redirects]]
  from = '/blogs/page/*' 
  to = 'http://15.222.45.215/'
  status = 200
  force = true

[[redirects]]
  from = '/post/page/*' 
  to = 'http://15.222.45.215/'
  status = 200
  force = true

[[redirects]] # cuando hacemos click en leer más de un artículo específico, redireccionar a /blog/:splat, que se mapea a blog.zircon.tech/:splat
  from = '/blog/nft-explained-what-are-nfts-and-how-are-they-used' 
  to = 'http://15.222.45.215/nft-explained-what-are-nfts-and-how-are-they-used'
  status = 200
  force = true

[[redirects]] # cuando hacemos click en leer más de un artículo específico, redireccionar a /blog/:splat, que se mapea a blog.zircon.tech/:splat
  from = '/blog/*' 
  to = 'http://15.222.45.215/:splat'
  status = 200
  force = true
  
 [[redirects]] # cuando hacemos click en ver todos los articulos, ir al index del Blog
  from = '/blog' 
  to = 'http://15.222.45.215'
  status = 301
  force = true

# Ejemplo: 
#                           /:splat                            
# https://zircon.tech/blog/zircontech-notarizer 
#    ▼                          
#                               /:splat
# https://blog.zircon.tech/blog/zircontech-notarizer


[[redirects]]
  from = '/blog/2020/04/02/cloud-business-cases-involving-blockchain-technologies' 
  to = 'http://15.222.45.215/cloud-business-cases-involving-blockchain-technologies'
  status = 301
  force = true

[[redirects]] # cuando hacemos click en leer más de un servicio específico, redireccionar a /info/:splat, que se mapea a info.zircon.tech/:splat
  from = '/info/*' 
  to = 'https://info.zircon.tech/en-us/:splat'
  status = 301
  force = true

# Ejemplo: 
#                           /:splat                            
# https://zircon.tech/info/zircontech-services-iot 
#    ▼                          
#                               /:splat
# https://info.zircon.tech/en-us/zircontech-services-iot

[[redirects]]
  from = '/blockchain-software-company' 
  to = 'https://info.zircon.tech/en-us/zircontech-services-blockchain'
  status = 301
  force = true

[build]
  command = "yarn build"
  publish = ".next"
